spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.23:3306/hs3d?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: noitom
    password: noitom